#!/bin/sh

NAME=$(basename $0)
ACTION="${1}"

# Container ID
get_cid() {
  POD_NAME="${1}"
  CONTAINER_ID=$(kubectl get po "${POD_NAME}" -o jsonpath='{.status.containerStatuses[0].containerID}' | sed -e 's#^docker://##g')
  echo "${CONTAINER_ID}"
}

get_pid() {
  CONTAINER_ID=$(get_cid "${1}")
  PID=$(docker inspect --format '{{ .State.Pid }}' "${CONTAINER_ID}")
  echo "${PID}"
}

case ${ACTION} in
  cid)
    get_cid "${2}"
  ;;
  pid)
    get_pid "${2}"
  ;;
  *)
    echo "-------------------------------------------------------------"
    echo "Usage: ${NAME} [cid|pid] <POD-NAME>"
    echo "-------------------------------------------------------------"
    echo " - cid: return container ID                                  "
    echo " - pid: return process ID                                    "
    echo "-------------------------------------------------------------"
  ;;
esac
